[shell] 
program = "$HOME/.config/alacritty/startup.sh"

[window]
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
opacity = 0.9
blur = true
decorations = "None"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
bold.family = "JetBrainsMono Nerd Font Mono"
italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.family = "JetBrainsMono Nerd Font Mono"
size = 12
offset.y = 1

[env]
term = "xterm-256color"


