local harpoon = require("harpoon")
harpoon:setup({})
nmap("<leader>a", function()
    harpoon:list():append()
end)
nmap("<C-e>", function() harpoon.ui:toggle_quick_menu(harpoon:list()) end)

nmap("<C-p>", function() harpoon:list():select(1) end)
nmap("<C-o>", function() harpoon:list():select(2) end)
nmap("<C-i>", function() harpoon:list():select(3) end)

-- nmap("<F6>", function() harpoon:list():select(1) end)
-- nmap("<F5>", function() harpoon:list():select(2) end)
-- nmap("<F4>", function() harpoon:list():select(3) end)
-- nmap("<F3>", function() harpoon:list():select(4) end)
