#!/bin/zsh
eval "$(/opt/homebrew/bin/brew shellenv)"

language=$(ls ~/projects | fzf-tmux -p)

if [[ -z "$language" ]];
then
    exit 0
fi

selected_name=$(ls ~/projects/$language | fzf-tmux -p )

if [[ -z "$selected_name" ]];
then
    exit 0
fi

selected_dir=~/projects/$language/$selected_name

tmux neww -c $selected_dir

