require("custom.after.plugin.colors")
require("custom.after.plugin.lsp")
require("custom.after.plugin.lazygit")
require("custom.after.plugin.lualine")
require("custom.after.plugin.harpoon")
require("custom.after.plugin.telescope")
require("custom.after.plugin.toggleterm")
require("custom.after.plugin.treesitter")
