require('plugins.cmp')
require('plugins.lualine')
require('plugins.mason')
require('plugins.null-ls')
require('plugins.nvim-tree')
require('plugins.startup')
require('plugins.telescope')
require('plugins.treesitter')
