#! /bin/bash
read -e -p "base path:" basePath
basePath=${basePath%/}


if [ ! -d "$basePath" ]; then
  exit 0

fi

selected=$(find $basePath -mindepth 1 -maxdepth 1 \( -name node_modules -o -name .git \) -prune -o -type d -print | fzf-tmux -p)

if [[ -z "$selected" ]]; 
then 
  exit 0
fi

vimcd ~/$basePath/$selected

