#! /bin/bash
#read -e -p "base path ~/" basePath
#basePath=${basePath%/}


#if [ ! -d "$basePath" ]; then
#  exit 0
#fi

language=$(ls ~/projects | fzf-tmux -p)

if [[ -z "$language" ]]; 
then 
  exit 0
fi

selected_name=$(ls ~/projects/$language | fzf-tmux -p )

if [[ -z "$selected_name" ]]; 
then 
  exit 0
fi

selected_dir=~/projects/$language/$selected_name
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && -[[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected_dir
    exit 0
fi

tmux neww -c $selected_dir -n $selected_dir -S 'nvim'

