#! /bin/bash
basePath=~/projects/personal

selected=$(find $basePath \( -name node_modules -o -name .git \) -prune -o -name '*' -type d -maxdepth 1  -print | cut -d/ -f6- | fzf-tmux -p)
# echo "$basePath/$selected"
vimcd $basePath/$selected
# exit 0
