require("custom.plugins.colors")
require("custom.plugins.lsp")
require("custom.plugins.lazygit")
require("custom.plugins.lualine")
require("custom.plugins.harpoon")
require("custom.plugins.telescope")
require("custom.plugins.toggleterm")
require("custom.plugins.treesitter")
